stages:
  - clear
  - build_go
  - build_image
  - deploy

Clear old tag:
  stage: clear
  image: bitnami/git:2-debian-11
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
  script:
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://gitlab-ci-token:${TAG_DELETE_TOKEN}@${url_host}"
    - if [[ "$CI_COMMIT_TAG" == *"$TAG_TESTING"* ]]; then VERSION_PREFIX=$(echo "$CI_COMMIT_TAG" | cut -d'+' -f1); (for TAG in $(git tag -l "$VERSION_PREFIX*"); do (if [ "$TAG" != "$CI_COMMIT_TAG" ]; then echo "$TAG"; git tag -d "$TAG"; git push --delete origin "$TAG"; fi); done) fi

Build binary:
  stage: build_go
  image: golang:1.18
  script:
    - go build -o $CI_PROJECT_DIR/binary main.go 
  artifacts:
    paths:
      - binary
    expire_in: 1 hour

Build docker image:
  stage: build_image
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/vneu/rest-api-pondasi-mftl:$(echo "$CI_COMMIT_TAG" | sed "s/+/-/" | sed "s/v//") .
    - docker push $CI_REGISTRY/vneu/rest-api-pondasi-mftl:$(echo "$CI_COMMIT_TAG" | sed "s/+/-/" | sed "s/v//")  

Deploy:
  stage: deploy
  image: debian:latest
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SERVER_VNEU_1_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 2122 $SERVER_VNEU_1_HOST >> ~/.ssh/known_hosts
  script:
    - scp -P 2122 -v docker-compose.yml $SERVER_VNEU_1_USER@$SERVER_VNEU_1_HOST:$APPLICATION_DIRECTORY
    - ssh -p 2122 $SERVER_VNEU_1_USER@$SERVER_VNEU_1_HOST "docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY && cd $APPLICATION_DIRECTORY && PORT=$PORT TAG=$(echo "$CI_COMMIT_TAG" | sed "s/+/-/" | sed "s/v//") docker-compose up -d"